### ISSUE TITLE
Something went wrong. Error code: 12

### ISSUE THREAD

**Issue by cebucul** [tink-ab/tink-link-web-example#118]
Hi,
I followed all steps described for setup and I have the server up, the 1st page loads, I get to choose locale. I went for GB and EN US then next page displays **Something went wrong. Error code: 12**

Please help as I could not locate this error code in your documentation.

thanks

**Comment by cebucul** [comment]
I found in chrome developer tools:
 POST https://api.tink.com/api/v1/oauth/describe 401
App is not allowed to notify customer back.

**Comment by rtelicak** [comment]
Hey! I think the issue is that the `redirect_uri` url you're passing when launching Tink Link is invalid. The `redirect_uri` you're passing should be present in your app's configuration available at http://console.tink.com. Also can you see in a response the reason why `/describe` call failed?

**Comment by cebucul** [comment]
Thank you Roman for taking time to reply.
In my Tink Console I had it already:
http://localhost:3000/callback

In the end I discovered I was not setting properly the environment variables correctly for MacOs. Now it works but I ran into another issue. Altough I have all connections enabled in my Tink console including test banks, when I launch this it will show only production connections live in a given country and since I have no account in any I basically fail to login. The Test Bank connection is not available at all. I tried removing all Prod Banks and leaving only Test Bank active but then I get an empty list on instance running on my local host. Please let me know if any suggestions on how to point this towards Test Bank.

Thank you

**Comment by cebucul** [comment]
I edited the right file to append   "&test=true";
and now I see only test banks which is good but still I have issues. The demo seems to go in circles. After I complete auth to a Demo Bank provider (tried 3-4) I get an intermediary screen displaying some went wrong then immediately redirected to a connection success page then after click on next button I land again on the home page where I choose my locale and language so in the end I do not see transactions, accounts out of Demo Banks
